service: serverless-b

provider:
  name: aws
  runtime: nodejs12.x


  stage: dev
  region: eu-west-1

functions:
  hello2:
    handler: handler.hello2

resources:
  Recources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-new-bucket-331b7f25-9217-4280-b70a-7a3a4a33ee80
