service: multistackdemo

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    environment:
      S3BUCKET_ARN:
        Fn::GetAtt:
         - ServerlessB
         - Outputs.TheBestBucketEverCreatedName

custom:
  nested-stacks:
    location: nested-stacks
    stacks:
      - id: ServerlessB
        template: serverless-b.yml

plugins:
  - serverless-aws-nested-stacks
